In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("D:\Data Science\Smart_Ship_Project\Vessel_Project\Data\engine_failure_dataset.csv")
df

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_26644\2991849005.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  df = pd.read_csv("D:\Data Science\Smart_Ship_Project\Vessel_Project\Data\engine_failure_dataset.csv")

,Time_Stamp,Temperature (°C),RPM,Fuel_Efficiency,Vibration_X,Vibration_Y,Vibration_Z,Torque,Power_Output (kW),Fault_Condition,Operational_Mode
0,2024-12-24 10:00:00,60.308585,3426.827588,20.445472,0.874657,0.005686,0.529798,107.877659,23.367684,2,Idle
1,2024-12-24 10:05:00,112.705055,2949.758424,23.083947,0.696461,0.391779,0.124336,60.351655,57.941022,3,Cruising
2,2024-12-24 10:10:00,108.670976,1817.971040,20.555326,0.495276,0.189714,0.886417,110.986564,47.732998,2,Cruising
3,2024-12-24 10:15:00,107.114691,2730.660539,23.226431,0.986206,0.983202,0.468114,77.416793,44.112039,2,Cruising
4,2024-12-24 10:20:00,118.075814,1854.488677,21.148226,0.710810,0.101139,0.481034,100.475881,80.681972,2,Cruising
...,...,...,...,...,...,...,...,...,...,...,...
995,2024-12-27 20:55:00,88.231211,1477.774501,23.749532,0.827987,0.664745,0.625331,178.466184,41.494154,3,Cruising
996,2024-12-27 21:00:00,105.241946,1617.745044,16.166110,0.753548,0.797969,0.618335,154.586204,52.987240,0,Cruising
997,2024-12-27 21:05:00,119.066775,2473.669785,17.657404,0.982960,0.699409,0.804165,164.138685,55.994142,3,Idle
998,2024-12-27 21:10:00,90.620157,2297.744136,17.479882,0.686213,0.875040,0.370690,78.687527,38.729023,1,Heavy Load
999,2024-12-27 21:15:00,93.144406,2511.308863,17.597145,0.950341,0.340887,0.072738,178.572291,83.769023,0,Cruising

In [4]:
df.columns

Index(['Time_Stamp', 'Temperature (°C)', 'RPM', 'Fuel_Efficiency',
       'Vibration_X', 'Vibration_Y', 'Vibration_Z', 'Torque',
       'Power_Output (kW)', 'Fault_Condition', 'Operational_Mode'],
      dtype='object')

In [6]:
updated_df = pd.read_csv("D:\Data Science\Smart_Ship_Project\Vessel_Project\Data\enhanced_ship_data.csv")
updated_df.columns

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_22700\1831028575.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  updated_df = pd.read_csv("D:\Data Science\Smart_Ship_Project\Vessel_Project\Data\enhanced_ship_data.csv")

Index(['Time_Stamp', 'Temperature (°C)', 'RPM', 'Fuel_Efficiency',
       'Vibration_X', 'Vibration_Y', 'Vibration_Z', 'Torque',
       'Power_Output (kW)', 'Fault_Condition', 'Operational_Mode', 'Defect_ID',
       'Root_Cause', 'Troubleshooting_Steps', 'Severity',
       'Remediation_Actions'],
      dtype='object')

In [9]:
modified_df = pd.read_csv("D:\Data Science\Smart_Ship_Project\Vessel_Project\Data\modified_ship_data.csv")
modified_df.columns

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_26644\1536087700.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  modified_df = pd.read_csv("D:\Data Science\Smart_Ship_Project\Vessel_Project\Data\modified_ship_data.csv")

Index(['Time_Stamp', 'Temperature (°C)', 'RPM', 'Fuel_Efficiency',
       'Vibration_X', 'Vibration_Y', 'Vibration_Z', 'Torque',
       'Power_Output (kW)', 'Fault_Condition', 'Operational_Mode', 'Vessel_ID',
       'Vessel_Type', 'Engine_Model', 'Expected_Temp', 'Defect_ID',
       'Root_Cause', 'Troubleshooting_Steps', 'Severity',
       'Remediation_Actions'],
      dtype='object')

In [10]:
modified_df

,Time_Stamp,Temperature (°C),RPM,Fuel_Efficiency,Vibration_X,Vibration_Y,Vibration_Z,Torque,Power_Output (kW),Fault_Condition,Operational_Mode,Vessel_ID,Vessel_Type,Engine_Model,Expected_Temp,Defect_ID,Root_Cause,Troubleshooting_Steps,Severity,Remediation_Actions
0,2024-12-24 10:00:00,60.308585,3426.827588,20.445472,0.874657,0.005686,0.529798,107.877659,23.367684,2,Idle,VSL-101,Cargo,Wartsila-X12,120,DEF-TEMP-NORM-001,Cooling efficiency is good.,Coolant level is normal.,Normal,No action taken. Continue regular monitoring.
1,2024-12-24 10:05:00,112.705055,2949.758424,23.083947,0.696461,0.391779,0.124336,60.351655,57.941022,3,Cruising,VSL-101,Cargo,Wartsila-X12,120,DEF-TEMP-HIGH-002,Possible thermostat malfunction,Inspect thermostat and cooling pump,High,Reduce engine load and inspect cooling system
2,2024-12-24 10:10:00,108.670976,1817.971040,20.555326,0.495276,0.189714,0.886417,110.986564,47.732998,2,Cruising,VSL-101,Cargo,Wartsila-X12,120,DEF-TEMP-HIGH-002,Possible thermostat malfunction,Inspect thermostat and cooling pump,High,Reduce engine load and inspect cooling system
3,2024-12-24 10:15:00,107.114691,2730.660539,23.226431,0.986206,0.983202,0.468114,77.416793,44.112039,2,Cruising,VSL-101,Cargo,Wartsila-X12,120,DEF-TEMP-HIGH-002,Possible thermostat malfunction,Inspect thermostat and cooling pump,High,Reduce engine load and inspect cooling system
4,2024-12-24 10:20:00,118.075814,1854.488677,21.148226,0.710810,0.101139,0.481034,100.475881,80.681972,2,Cruising,VSL-101,Cargo,Wartsila-X12,120,DEF-TEMP-HIGH-002,Possible thermostat malfunction,Inspect thermostat and cooling pump,High,Reduce engine load and inspect cooling system
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2024-12-27 20:55:00,88.231211,1477.774501,23.749532,0.827987,0.664745,0.625331,178.466184,41.494154,3,Cruising,VSL-103,Container Ship,Sulzer RT-flex96C,120,DEF-TEMP-WARN-001,Cooling efficiency degradation,Inspect coolant level and radiator airflow,Warning,Monitor engine temperature continuously
996,2024-12-27 21:00:00,105.241946,1617.745044,16.166110,0.753548,0.797969,0.618335,154.586204,52.987240,0,Cruising,VSL-103,Container Ship,Sulzer RT-flex96C,120,DEF-TEMP-HIGH-002,Possible thermostat malfunction,Inspect thermostat and cooling pump,High,Reduce engine load and inspect cooling system
997,2024-12-27 21:05:00,119.066775,2473.669785,17.657404,0.982960,0.699409,0.804165,164.138685,55.994142,3,Idle,VSL-103,Container Ship,Sulzer RT-flex96C,120,DEF-TEMP-HIGH-002,Possible thermostat malfunction,Inspect thermostat and cooling pump,High,Reduce engine load and inspect cooling system
998,2024-12-27 21:10:00,90.620157,2297.744136,17.479882,0.686213,0.875040,0.370690,78.687527,38.729023,1,Heavy Load,VSL-103,Container Ship,Sulzer RT-flex96C,120,DEF-TEMP-WARN-001,Cooling efficiency degradation,Inspect coolant level and radiator airflow,Warning,Monitor engine temperature continuously
999,2024-12-27 21:15:00,93.144406,2511.308863,17.597145,0.950341,0.340887,0.072738,178.572291,83.769023,0,Cruising,VSL-103,Container Ship,Sulzer RT-flex96C,120,DEF-TEMP-WARN-001,Cooling efficiency degradation,Inspect coolant level and radiator airflow,Warning,Monitor engine temperature continuously